#! /usr/bin/ruby
require 'rubygems'
require 'rainbow'

require File.join(File.dirname(__FILE__), 'lib', 'config')
require File.join(File.dirname(__FILE__), 'lib', 'deployer')

include SunRaise::PubConf

at_exit { SunRaise::Deployer.new.go! }

remote_host 'twews.com'
remote_user 'root'

git_url 'git://github.com/Paxa/web-configs.git'

deploy_to '/tmp/deploy/test2'
then_link_to '/tmp/www/test'

shared_dirs ['lib']
linked_dirs ['logs', 'tmp']

local_project_path "/home/paxa/Dropbox/configs"
